### ISSUE TITLE
Random play function calling wrong serial code

### ISSUE THREAD

**Issue by blueloofah** [bablokb/circuitpython-dfplayer#4]
I'm attempting to set the dfplayer into random playback mode but it hard loops all the contents of the folder randomly if the dfplayer.random() is used during initialization. I only suspect the lib might be the issue due to the serial command for random play is set to 0x18 where as the wiki lists it as 0x08(3) and the loop function in the lib is set to 0x08. It's very possible this could be an issue directly related to the code I'm running but I just wanted to verify whether or not this if this is a conflict within the library itself.

**Comment by bablokb** [comment]
Yes, seems like the library is wrong. `random()` and `loop` should send 0x08 followed by 0x03 (random) or 0x00 (loop).

Note that this is a library I ported from a MicroPython implementation and  I did not test every function. And maybe the hardware of the orginal author was a bit different.

Anyway, if you could change the lib and test it and report back, that would be great (I don't have a dfplayer currently setup for testing). A pull request would be great, but not necessary if this is too much  hassle for you.

**Comment by blueloofah** [comment]
Ah well, while I can try my hand at adjusting the lib, my coding skills are novice at best. That said I will do what I can on my end to see if I can get it working properly, and if I do I will report back.

**Comment by bablokb** [comment]
If you run into problems, just ask for help. I could give you the code lines to try, but maybe figuring them out yourself is of more use to you. We all started out as novices.

**Comment by blueloofah** [comment]
Thank you, I appreciate the encouragement. I'll reach out if I end up hitting a brick wall.

**Comment by bmoren** [comment]
only ever getting...

Traceback (most recent call last):
  File "code.py", line 11, in <module>
  File "/lib/DFPlayer.py", line 50, in __init__
Exception: DFPlayer could not be initialized.

**Comment by bablokb** [comment]
@bmoren 

This does not seem to be related to this specific issue (see title). You are not failing calling `random()`, you already fail during initialization.

Could you please open a new issue and give some more information (more code, which device, which CP version). Thanks.

**Comment by bmoren** [comment]
whoops meant to put this in a new issue! My mistake!

**Comment by bablokb** [comment]
I am closing this issue since the original posting refers to wrong serial codes for `random()` and `loop()`. It turns out that the wiki is wrong, at least the docs don't not match the sample implementation of DFRobot.
